# Generated by Django 3.2.6 on 2021-08-11 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alpha_Gallery_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='username',
        ),
    ]
