# Generated by Django 3.2.6 on 2021-08-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alpha_Gallery_App', '0003_auto_20210812_0641'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='username',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
