# Generated by Django 3.2.6 on 2021-08-12 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Alpha_Gallery_App', '0004_posts_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='username',
        ),
    ]
