# Generated by Django 3.2.6 on 2021-08-12 07:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alpha_Gallery_App', '0005_remove_posts_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='comments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
    ]
