# Generated by Django 3.2.6 on 2021-08-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alpha_Gallery_App', '0006_alter_posts_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
